name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight UTC
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake game from GitHub contribution grid
        uses: Platane/snk@v3.3.0
        with:
          github_user: jsfl-24
          png_width: 1000
          png_height: 1000
          cell_size: 1 # Ensures each cell matches a contribution box
          # You can adjust the width and height to fit your preference

      - name: Commit and push generated snake image
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update snake game image"
          file_pattern: "*.png"
          branch: main # or master, depending on your default branch name
